export const languages = {
    names: [
        "",
        "Esperanto",
        "English",
        "Spanish",
        "French",
        "German",
        "Italian",
        "Ukrainian",
        "Polish",
        "Mandarin",
        "Hindi",
        "Russian",
        "Arabic",
        "Bengali",
        "Korean",
        "Portuguese",
        "Urdu",
        "Indonesian",
        "Japanese",
        "Turkish",
        "Other",
    ],
    levels: ["", "A1", "A2", "B1", "B2", "C1"],
};
