export default {
    names: [
        "Esperanto",
        "English",
        "Spanish",
        "French",
        "German",
        "Italian",
        "Ukrainian",
        "Polish",
        "Mandarin",
        "Hindi",
        "Russian",
        "Arabic",
        "Bengali",
        "Korean",
        "Portuguese",
        "Urdu",
        "Indonesian",
        "Japanese",
        "Turkish",
        "Other",
    ],
    levels: [
        "Beginner",
        "Pre Intermediate",
        "Intermediate",
        "Upper Intermediate",
        "Advanced",
    ],
};
